---
title: "project1"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(dplyr)
library(dplyr)
library(readxl)
```

```{r Occupational Group}
occ_group_overall <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Aranılan meslek grubuna göre işsizler.xls", range = "TÜRKİYE!A7:L92", col_names = c("year", "month", "total_unemployed", "manager", "prof", "tech", "cleric", "service", "agricul", "trade", "operator", "elemantary"))

occ_group_male <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Aranılan meslek grubuna göre işsizler.xls", range = "TÜRKİYE!N7:Y92", col_names = c("year", "month", "total_unemployed", "manager", "prof", "tech", "cleric", "service", "agricul", "trade", "operator", "elemantary"))

occ_group_female <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Aranılan meslek grubuna göre işsizler.xls", range = "TÜRKİYE!AA6:AL91", col_names = c("year", "month", "total_unemployed", "manager", "prof", "tech", "cleric", "service", "agricul", "trade", "operator", "elemantary"))

```

```{r Job Searching Channel}
job_search_overall <- read_xls("/Users/Toshiba/Desktop/Rhapsody/İş aradıkları kanala göre işsizler.xls", range = "TÜRKİYE!A7:P91", col_names = c("year", "month", "total_unemployed", "to_employers", "to_relatives", "to_emp_office", "to_emp_agencies", "to_newspaper", "insert_ad_to_newspaper", "take_interview", "look_place/equip_to_est_bus", "look_credit/license_to_est_bus", "wait_call_from_emp_office", "wait_result_of_app", "wait_result_of_comp_for_public_sec", "others"))

job_search_male <- read_xls("/Users/Toshiba/Desktop/Rhapsody/İş aradıkları kanala göre işsizler.xls", range = "TÜRKİYE!R7:AG91", col_names = c("year", "month", "total_unemployed", "to_employers", "to_relatives", "to_emp_office", "to_emp_agencies", "to_newspaper", "insert_ad_to_newspaper", "take_interview", "look_place/equip_to_est_bus", "look_credit/license_to_est_bus", "wait_call_from_emp_office", "wait_result_of_app", "wait_result_of_comp_for_public_sec", "others"))

job_search_female <- read_xls("/Users/Toshiba/Desktop/Rhapsody/İş aradıkları kanala göre işsizler.xls", range = "TÜRKİYE!AI7:AX91", col_names = c("year", "month", "total_unemployed", "to_employers", "to_relatives", "to_emp_office", "to_emp_agencies", "to_newspaper", "insert_ad_to_newspaper", "take_interview", "look_place/equip_to_est_bus", "look_credit/license_to_est_bus", "wait_call_from_emp_office", "wait_result_of_app", "wait_result_of_comp_for_public_sec", "others"))
```


```{r Last Graduated Major}
last_graduated_major <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Yüksekokul ve fakülte mezunlarının en son mezun oldukları alana göre işgücü durumu.xls", range = "TURKIYE!A6:Y41", col_names = c("year", "statistics", "higher_ed_grad", "education", "arts", "humanities", "languages", "social_sci", "journalism", "business", "law", "biology_env_related_sci", "physical_sci", "math_stat", "info_communication_tech", "engineering", "manufacturing_processing", "architecture_construction", "agriculture_forestry_fishery", "veterinary", "health", "welfare", "personal_services", "occupational_health_transport_services", "security_services"))

```


```{r Educational Level}
educational_level_overall <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Eğitim durumuna göre işgücü durumu.xls", range = "TÜRKİYE!A7:Q92", col_names = c("year", "month", "lf_illeterate", "lf_less_than_hs", "lf_highschool", "lf_voc_hs", "lf-_higher_ed","emp_illeterate", "emp_less_than_hs", "emp_highschool", "emp_voc_hs", "emp_higher_ed","unemp_illeterate", "unemp_less_than_hs", "unemp_highschool", "unemp_voc_hs", "unemp_higher_ed" ))

educational_level_male <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Eğitim durumuna göre işgücü durumu.xls", range = "TÜRKİYE!AK7:BA92", col_names = c("year", "month", "lf_illeterate", "lf_less_than_hs", "lf_highschool", "lf_voc_hs", "lf-_higher_ed","emp_illeterate", "emp_less_than_hs", "emp_highschool", "emp_voc_hs", "emp_higher_ed","unemp_illeterate", "unemp_less_than_hs", "unemp_highschool", "unemp_voc_hs", "unemp_higher_ed" ))

educational_level_female <- read_xls("/Users/Toshiba/Desktop/Rhapsody/Eğitim durumuna göre işgücü durumu.xls", range = "TÜRKİYE!BW7:CM92", col_names = c("year", "month", "lf_illeterate", "lf_less_than_hs", "lf_highschool", "lf_voc_hs", "lf-_higher_ed","emp_illeterate", "emp_less_than_hs", "emp_highschool", "emp_voc_hs", "emp_higher_ed","unemp_illeterate", "unemp_less_than_hs", "unemp_highschool", "unemp_voc_hs", "unemp_higher_ed" ))
```
